export { default as CreateProduct } from "./CreateProduct"
export { default as Dashboard } from "./Dashboard"
export { default as Home } from "./Home"
export { default as SingleProductDet } from "./SingleProductDet"
export { default as UpdateSellerProduct } from "./UpdateSellerProduct"